#https://docs.ansible.com/ansible/latest/modules/ec2_module.html
#Create a EC2 Instances
#Add instance to host group

- name: Create a EC2 instance
  hosts: localhost
  gather_facts: False
  
  #Variables
  vars:
    keypair: DevOps-yks
    instance_type: t2.micro              
    security_group: DevOps-NSG
    image: ami-0019ef04ac50be30f
    region: us-west-1

  tasks:
    - name: Launch instance
      ec2:
         key_name: "{{ keypair }}"
         group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         #vpc_subnet_id: subnet-29e63245
         exact_count: 2
         count_tag:
            Name: ByAnsible
         instance_tags:
            Name: aws_ec2_v2_ansible
         #assign_public_ip: yes
      register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: aws-launched
      with_items: "{{ ec2.instances }}"

    #- name: Wait for SSH to come up
     # delegate_to: "{{ item.public_dns_name }}"
      #wait_for_connection:
       # delay: 60
        #timeout: 320
      #with_items: "{{ ec2.instances }}"

# Terminate every running instance in a region. Use with EXTREME caution.
#- ec2_instance:
 #   state: absent
  #  filters:
   #   instance-state-name: running

# restart a particular instance by its ID
#- ec2_instance:
 #   state: restarted
  #  instance_ids:
   #   - i-12345678